### PR TITLE
Fix input panel bugs

### LINKED ISSUE #346: Can't move key focus on software keyboard when using FlutterRendererType.EvasGL
Recently evas gl renderer has been made available for all profiles. however, during testing it was discovered that the key focus could not be moved on the software keyboard.

image 

Related log
``` bash
[I] flutter_tizen_view.cc: OnKey(252) > Key symbol: Right, code: 0x00000072
[I] text_input_channel.cc: HandleKey(322) > Key[Right] is unhandled.
[I] flutter_tizen_view.cc: OnKey(252) > Key symbol: Right, code: 0x00000072
[I] text_input_channel.cc: HandleKey(322) > Key[Right] is unhandled.
[I] flutter_tizen_view.cc: OnKey(252) > Key symbol: Down, code: 0x00000074
[I] text_input_channel.cc: HandleKey(322) > Key[Down] is unhandled.
[I] flutter_tizen_view.cc: OnKey(252) > Key symbol: Down, code: 0x00000074
[I] text_input_channel.cc: HandleKey(322) > Key[Down] is unhandled.
[I] flutter_tizen_view.cc: OnKey(252) > Key symbol: Left, code: 0x00000071
[I] text_input_channel.cc: HandleKey(322) > Key[Left] is unhandled.
[I] flutter_tizen_view.cc: OnKey(252) > Key symbol: Left, code: 0x00000071
[I] text_input_channel.cc: HandleKey(322) > Key[Left] is unhandled.
[I] flutter_tizen_view.cc: OnKey(252) > Key symbol: Up, code: 0x0000006f
[I] text_input_channel.cc: HandleKey(322) > Key[Up] is unhandled.
[I] flutter_tizen_view.cc: OnKey(252) > Key symbol: Up, code: 0x0000006f
[I] text_input_channel.cc: HandleKey(322) > Key[Up] is unhandled.
[I] flutter_tizen_view.cc: OnKey(252) > Key symbol: Left, code: 0x00000071
[I] text_input_channel.cc: HandleKey(322) > Key[Left] is unhandled.
[I] flutter_tizen_view.cc: OnKey(252) > Key symbol: Left, code: 0x00000071
[I] text_input_channel.cc: HandleKey(322) > Key[Left] is unhandled.
[I] flutter_tizen_view.cc: OnKey(252) > Key symbol: Left, code: 0x00000071
[I] text_input_channel.cc: HandleKey(322) > Key[Left] is unhandled.
[I] flutter_tizen_view.cc: OnKey(252) > Key symbol: Left, code: 0x00000071
[I] text_input_channel.cc: HandleKey(322) > Key[Left] is unhandled.

```

### PR DESCRIPTION
**Pull request by bbrto21**
* Resolve #346.
* Corrects deleting character in text composition.
* Now, filter makes the key focus move work properly, so no longer need to ignore specific key event handling.

Signed-off-by: Boram Bae <boram21.bae@samsung.com>

### CODE REVIEW

File: shell/platform/tizen/tizen_input_method_context.cc [hunk 1]
```diff
@@ -83,19 +83,33 @@ Ecore_IMF_Keyboard_Locks EcoreInputModifiersToEcoreImfLocks(
...
+
   imf_event.modifiers =
       EcoreInputModifiersToEcoreImfModifiers(event->modifiers);
   imf_event.locks = EcoreInputModifiersToEcoreImfLocks(event->modifiers);
-  imf_event.dev_name = dev_name;
-  imf_event.keycode = event->keycode;
+
+  if (event->dev) {
+    imf_event.dev_name = ecore_device_name_get(event->dev)
+                             ? ecore_device_name_get(event->dev)
```
Comment (JSUYA) [inline shell/platform/tizen/tizen_input_method_context.cc:102]: How about using a local variable rather than calling the same function twice?
like this?
```
const char* device_name = ecore_device_name_get(event->dev);
imf_event.dev_name = device_name ? device_name : "";
```

**Comment by bbrto21** [comment]
This PR didn't working properly in TV device... :(

**Review by JSUYA — APPROVED** [review]
good 👍

**Comment by JSUYA** [comment]
> This PR didn't working properly in TV device... :(

oh i tested only on emulator...

File: shell/platform/tizen/tizen_input_method_context.cc (hunk 1 above)
Comment (bbrto21) [reply shell/platform/tizen/tizen_input_method_context.cc]: I updated it.
